question 1 answer
NSS-Full-Time-Data-Analytics-9/lahman_baseball-die-hard pull request #1
Opened 2023-02-14 20:57 UTC by markrmath

answers question 1

2023-02-14 21:00 UTC, WilliamPrunty commented
I think we should have the question asked on each script as well.

2023-02-14 21:04 UTC, WilliamPrunty requested changes
I think we should add the question to each script as well.

2023-02-14 21:47 UTC, WilliamPrunty approved these changes
Looks good!

2023-02-15 15:19 UTC, eykinnard approved these changes
Looks good!

2023-02-15 15:22 UTC, merged